export const codeLanguages = [
    { label: "JavaScript", value: "javascript" },
    { label: "Python", value: "python" },
    { label: "Java", value: "java" },
    { label: "C++", value: "cpp" },
    { label: "C#", value: "csharp" },
    { label: "Ruby", value: "ruby" },
    { label: "PHP", value: "php" },
    { label: "HTML", value: "html" },
    { label: "CSS", value: "css" },
    { label: "TypeScript", value: "typescript" },
    { label: "Go", value: "go" },
    { label: "Rust", value: "rust" },
    { label: "Swift", value: "swift" },
    { label: "Kotlin", value: "kotlin" },
    { label: "SQL", value: "sql" },
    { label: "MATLAB", value: "matlab" },
    { label: "Perl", value: "perl" },
    { label: "R", value: "r" },
    { label: "Dart", value: "dart" },
    { label: "Lua", value: "lua" },
    { label: "Shell", value: "shell" },
    { label: "Haskell", value: "haskell" },
    // Add more languages as needed
  ];