name: CI Pipeline
on:
  push:
    branches:
      - CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Start PostgreSQL
        uses: postgresql/setup-postgres@v2
        with:
          postgresql-version: '13'
          postgresql-database: 'cs3219_g47'
          postgresql-username: 'postgres'
          postgresql-password: ${{ secrets.PG_DB_PASSWORD }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: '6.0'

      - name: Install dependencies
        run: npm run install-all

      - name: Run Tests
        run: npm run test-ci
        env:
          ACCESS_TOKEN_SECRET: ${{ secrets.AUTH_TOKEN }}
